### ISSUE TITLE
How to update the app for F-Droid?

### ISSUE THREAD

**Issue by linsui** [corphish/TextTools#2]
This version code scheme doesn't work well with F-Droid because F-Droid always archive old apks with low version code so multi variant will be archived. And we can't set different version name suffix with autoupdate. It would be better if this can be changed with an option in runtime. Or you can use different appid.

**Comment by licaon-kter** [comment]
Why can't this be like an option in the app that the user can just toggle on/off as they wish?

**Comment by corphish** [comment]
Apart from some code being different, the 2 variants use different manifest files (major difference actually lies in the manifest). I am not sure if it is possible to dynamically modify manifest file depending on user selection, which is why I went with these 2 variants.

If I use different app ids, do we need a new F-Droid app entry or will the existing entry be able to handle them (with some changes)?

I am fine with reverting versionCode and versionName to how it was represented before which worked with F-Droid. I am also fine if F-Droid is able to detect and serve only 1 variant (multi). Let me know how can I proceed with having different app ids, or if there is something else that we can do? Thanks.

**Comment by linsui** [comment]
We need to add another metadata for another variant. :) You just need to change the appid of the single variant and I'll add the metadata.

**Comment by corphish** [comment]
https://github.com/corphish/TextTools/commit/291a4eb36e9a1d213e39ce5c41d4c7fa93dcbe1a

I have drafted a release with this change (along with some other minor changes). Let me know if it is ok, I will publish it then.
So, the multi variant will go by the original package name `com.corphish.quicktools` while the single variant will go by the package name `com.corphish.quicktools.single`. Both of them will share the same versionName and versionCode.
